apiVersion: v1
kind: Namespace
metadata:
  name: adoption-system
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adoptions
  namespace: adoption-system
spec:
  selector:
    matchLabels:
      app: adoptions
  template:
    metadata:
      labels:
        app: adoptions
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: adoptions
        image: adoptions-image
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---

# apiVersion: v1
# kind: Service
# metadata:
#   name: adoptions
#   namespace: adoption-system
# spec:
#   type: ClusterIP
#   selector:
#     app: adoptions
